// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxpdsufhfaicvgsjqnle.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4cGRzdWZoZmFpY3Znc2pxbmxlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMTA4MzYsImV4cCI6MjA1OTg4NjgzNn0.OH-Uhtp2716LxioX5jiQIuA2mpaBXv6h7KBGReyx9Js";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Define a custom type that extends Database with our tables
type CustomDatabase = Database & {
  public: {
    Tables: {
      profiles: {
        Row: Profile
        Insert: Omit<Profile, 'id' | 'created_at' | 'updated_at'>
        Update: Partial<Profile>
      },
      recycling_activities: {
        Row: RecyclingActivity
        Insert: Omit<RecyclingActivity, 'id'>
        Update: Partial<RecyclingActivity>
      },
      qr_codes: {
        Row: QrCode
        Insert: Omit<QrCode, 'id' | 'created_at'>
        Update: Partial<QrCode>
      },
      user_roles: {
        Row: UserRole
        Insert: Omit<UserRole, 'id' | 'created_at'>
        Update: Partial<UserRole>
      },
      milestones: {
        Row: Milestone
        Insert: Omit<Milestone, 'id' | 'created_at'>
        Update: Partial<Milestone>
      },
      recycling_locations: {
        Row: RecyclingLocation
        Insert: Omit<RecyclingLocation, 'id' | 'created_at' | 'updated_at'>
        Update: Partial<RecyclingLocation>
      },
      recycling_items: {
        Row: RecyclingItem
        Insert: Omit<RecyclingItem, 'id' | 'created_at' | 'updated_at'>
        Update: Partial<RecyclingItem>
      },
      reward_products: {
        Row: RewardProduct
        Insert: Omit<RewardProduct, 'id' | 'created_at' | 'updated_at'>
        Update: Partial<RewardProduct>
      },
      reward_coupons: {
        Row: RewardCoupon
        Insert: Omit<RewardCoupon, 'id' | 'created_at'>
        Update: Partial<RewardCoupon>
      },
      reward_partners: {
        Row: RewardPartner
        Insert: Omit<RewardPartner, 'id' | 'created_at'>
        Update: Partial<RewardPartner>
      },
      user_redemptions: {
        Row: UserRedemption
        Insert: Omit<UserRedemption, 'id'>
        Update: Partial<UserRedemption>
      }
    }
  }
}

// Create the client with our custom type and proper auth configuration
export const supabase = createClient<CustomDatabase>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storage: localStorage
  }
});

// Custom type definitions for our database schema
// These are used throughout the application but don't modify the generated types.ts file
export interface Profile {
  id: string;
  name: string;
  email: string;
  phone?: string;
  address?: string;
  photo_url?: string;
  points: number;
  level: string;
  created_at: string;
  updated_at: string;
  isAdmin?: boolean;
}

export interface Milestone {
  id: number;
  label: string;
  points: number;
  icon: string;
  created_at: string;
}

export interface RecyclingActivity {
  id: string;
  user_id: string;
  location_id?: string;
  item_id?: string;
  points: number;
  description: string;
  timestamp: string;
  photo_url?: string;
  qr_code?: string;
  status: string;
}

export interface RecyclingLocation {
  id: string;
  name: string;
  address: string;
  latitude?: number;
  longitude?: number;
  description?: string;
  photo_url?: string;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface RecyclingItem {
  id: string;
  name: string;
  category: string;
  points: number;
  image_url?: string;
  description?: string;
  barcode?: string;
  created_at: string;
  updated_at: string;
}

export interface QrCode {
  id: string;
  code: string;
  item_id?: string;
  points: number;
  is_used: boolean;
  created_by?: string;
  used_by?: string;
  created_at: string;
  used_at?: string;
}

export interface UserRole {
  id: string;
  user_id: string;
  role: 'user' | 'admin';
  created_at: string;
}

export interface RewardProduct {
  id: string;
  name: string;
  description: string;
  image_url?: string;
  point_cost: number;
  stock: number;
  created_at: string;
  updated_at: string;
}

export interface RewardCoupon {
  id: string;
  brand: string;
  description: string;
  code: string;
  point_cost: number;
  logo_url?: string;
  created_at: string;
  updated_at: string;
}

export interface RewardPartner {
  id: string;
  partner_name: string;
  offer: string;
  description: string;
  logo_url?: string;
  point_cost: number;
  created_at: string;
  updated_at: string;
}

export interface UserRedemption {
  id: string;
  user_id: string;
  redemption_type: string;
  redemption_id: string;
  points_spent: number;
  redeemed_at: string;
  status: string;
}
